package me.jessyan.mvparms.demo.drawables;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.ColorFilter;
import android.graphics.Paint;

import com.github.megatronking.svg.support.SVGRenderer;

/**
 * AUTO-GENERATED FILE.  DO NOT MODIFY.
 * 
 * This class was automatically generated by the
 * SVG-Generator. It should not be modified by hand.
 */
public class ic_alipay extends SVGRenderer {

    public ic_alipay(Context context) {
        super(context);
        mAlpha = 1.0f;
        mWidth = dip2px(24.0f);
        mHeight = dip2px(24.0f);
    }

    @Override
    public void render(Canvas canvas, int w, int h, ColorFilter filter) {
        final float scaleX = w / 24.0f;
        final float scaleY = h / 24.0f;
        
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(22.7357f, 20.8227f);
        mPath.cubicTo(21.457f, 20.2511f, 21.348f, 19.9741f, 20.0663f, 19.4084f);
        mPath.cubicTo(19.0498f, 18.9576f, 18.0244f, 18.5215f, 17.0079f, 18.0707f);
        mPath.cubicTo(16.1357f, 17.6848f, 15.2665f, 17.287f, 14.3973f, 16.8892f);
        mPath.cubicTo(14.0968f, 16.7507f, 14.0084f, 16.7979f, 13.7698f, 17.0336f);
        mPath.cubicTo(13.2335f, 17.564f, 12.6855f, 18.0825f, 12.1168f, 18.5775f);
        mPath.cubicTo(11.4656f, 19.1432f, 10.7231f, 19.5793f, 9.9541f, 19.9594f);
        mPath.cubicTo(9.1822f, 20.3395f, 8.3748f, 20.6371f, 7.5263f, 20.7991f);
        mPath.cubicTo(6.7219f, 20.9523f, 5.9087f, 21.026f, 5.0984f, 20.9229f);
        mPath.cubicTo(3.7401f, 20.752f, 2.4938f, 20.313f, 1.548f, 19.2611f);
        mPath.cubicTo(0.7053f, 18.3241f, 0.3694f, 17.2251f, 0.5167f, 15.9729f);
        mPath.cubicTo(0.5992f, 15.2834f, 0.7966f, 14.6293f, 1.1796f, 14.0577f);
        mPath.cubicTo(1.4271f, 13.6894f, 1.7542f, 13.3623f, 2.0989f, 13.0795f);
        mPath.cubicTo(2.868f, 12.4431f, 3.7902f, 12.172f, 4.7713f, 12.1219f);
        mPath.cubicTo(5.5433f, 12.0836f, 6.3212f, 12.06f, 7.0931f, 12.0983f);
        mPath.cubicTo(7.6647f, 12.1248f, 8.2305f, 12.2515f, 8.7962f, 12.3517f);
        mPath.cubicTo(9.3442f, 12.4489f, 9.8922f, 12.5462f, 10.4285f, 12.6876f);
        mPath.cubicTo(11.1857f, 12.888f, 11.9341f, 13.1266f, 12.6884f, 13.3476f);
        mPath.cubicTo(12.7444f, 13.3653f, 12.8004f, 13.38f, 12.8564f, 13.3977f);
        mPath.cubicTo(13.1746f, 13.5038f, 13.2335f, 13.5008f, 13.3631f, 13.1856f);
        mPath.cubicTo(13.7049f, 12.3488f, 14.0231f, 11.5031f, 14.3473f, 10.6605f);
        mPath.cubicTo(14.3885f, 10.5514f, 14.4032f, 10.4306f, 14.4386f, 10.3216f);
        mPath.cubicTo(14.4828f, 10.1772f, 14.418f, 10.1537f, 14.2913f, 10.1537f);
        mPath.cubicTo(13.5281f, 10.1566f, 12.765f, 10.1507f, 12.0019f, 10.1507f);
        mPath.lineTo(5.449f, 10.133f);
        mPath.cubicTo(5.3047f, 10.133f, 5.1603f, 10.136f, 5.0159f, 10.1213f);
        mPath.cubicTo(4.9658f, 10.1154f, 4.8863f, 10.0564f, 4.8863f, 10.0211f);
        mPath.cubicTo(4.8745f, 9.7589f, 4.8804f, 9.4996f, 4.8804f, 9.2255f);
        mPath.cubicTo(4.9511f, 9.2197f, 5.0012f, 9.2079f, 5.0513f, 9.2079f);
        mPath.cubicTo(6.5127f, 9.2108f, 7.9712f, 9.2167f, 9.4326f, 9.2255f);
        mPath.cubicTo(9.5622f, 9.2255f, 9.5976f, 9.1755f, 9.5976f, 9.0664f);
        mPath.cubicTo(9.6006f, 8.539f, 9.5976f, 8.0146f, 9.6035f, 7.4872f);
        mPath.cubicTo(9.6064f, 7.3251f, 9.4974f, 7.3516f, 9.4031f, 7.3516f);
        mPath.cubicTo(8.0802f, 7.3369f, 6.7602f, 7.3222f, 5.4372f, 7.3104f);
        mPath.cubicTo(4.9776f, 7.3074f, 4.515f, 7.3074f, 4.0554f, 7.3045f);
        mPath.cubicTo(3.9905f, 7.3045f, 3.9287f, 7.2986f, 3.855f, 7.2956f);
        mPath.lineTo(3.855f, 6.3351f);
        mPath.cubicTo(3.9051f, 6.3292f, 3.9434f, 6.3204f, 3.9817f, 6.3204f);
        mPath.cubicTo(4.8833f, 6.3204f, 5.7849f, 6.3174f, 6.6865f, 6.3263f);
        mPath.cubicTo(7.5675f, 6.3322f, 8.4485f, 6.3498f, 9.3295f, 6.3616f);
        mPath.cubicTo(9.6123f, 6.3646f, 9.6123f, 6.3587f, 9.6123f, 6.0758f);
        mPath.cubicTo(9.6153f, 5.4188f, 9.6241f, 4.7588f, 9.6182f, 4.1017f);
        mPath.cubicTo(9.6123f, 3.6155f, 9.7508f, 3.5743f, 10.1545f, 3.4977f);
        mPath.cubicTo(10.6053f, 3.4093f, 11.0826f, 3.4623f, 11.5481f, 3.4564f);
        mPath.cubicTo(11.8693f, 3.4535f, 12.1905f, 3.4564f, 12.5293f, 3.4564f);
        mPath.lineTo(12.5293f, 6.3822f);
        mPath.lineTo(18.764f, 6.3822f);
        mPath.lineTo(18.764f, 7.3752f);
        mPath.lineTo(12.5234f, 7.3752f);
        mPath.cubicTo(12.5234f, 7.5814f, 12.5264f, 7.7818f, 12.5234f, 7.9822f);
        mPath.cubicTo(12.5175f, 8.3357f, 12.5175f, 8.6922f, 12.5028f, 9.0458f);
        mPath.cubicTo(12.4969f, 9.2049f, 12.5499f, 9.2462f, 12.7061f, 9.2462f);
        mPath.cubicTo(13.7904f, 9.2403f, 14.8776f, 9.2432f, 15.9619f, 9.2491f);
        mPath.cubicTo(16.4687f, 9.2521f, 16.9725f, 9.2668f, 17.4793f, 9.2786f);
        mPath.cubicTo(17.5117f, 9.2786f, 17.5412f, 9.2874f, 17.6119f, 9.2992f);
        mPath.cubicTo(17.5117f, 9.6557f, 17.4204f, 10.0034f, 17.3202f, 10.3452f);
        mPath.cubicTo(16.9283f, 11.6564f, 16.3508f, 12.888f, 15.7439f, 14.1107f);
        mPath.cubicTo(15.626f, 14.3464f, 15.6348f, 14.3612f, 15.8823f, 14.4437f);
        mPath.cubicTo(16.6779f, 14.7177f, 17.4734f, 14.9976f, 18.269f, 15.2687f);
        mPath.cubicTo(18.9496f, 15.4985f, 19.6361f, 15.7165f, 20.3167f, 15.9464f);
        mPath.cubicTo(21.0239f, 16.185f, 21.7251f, 16.4355f, 22.4323f, 16.6741f);
        mPath.cubicTo(22.9214f, 16.8391f, 23.4164f, 16.9865f, 23.9084f, 17.1426f);
        mPath.cubicTo(23.9025f, 18.4626f, 22.7357f, 19.4939f, 22.7357f, 20.8227f);
        mPath.close();
        mPath.moveTo(22.7357f, 20.8227f);
        mPath.moveTo(5.4137f, 13.6894f);
        mPath.cubicTo(4.4001f, 13.6305f, 3.5221f, 13.8691f, 2.7206f, 14.3582f);
        mPath.cubicTo(1.8396f, 14.8974f, 1.4006f, 15.693f, 1.5185f, 16.7419f);
        mPath.cubicTo(1.5863f, 17.343f, 1.9015f, 17.7997f, 2.3671f, 18.1915f);
        mPath.cubicTo(3.0418f, 18.7573f, 3.8226f, 19.0902f, 4.6682f, 19.214f);
        mPath.cubicTo(5.8969f, 19.3907f, 7.1049f, 19.2081f, 8.2481f, 18.716f);
        mPath.cubicTo(9.7037f, 18.0884f, 10.841f, 17.0807f, 11.6984f, 15.7519f);
        mPath.cubicTo(11.7839f, 15.6193f, 11.775f, 15.5427f, 11.6306f, 15.4573f);
        mPath.cubicTo(10.4344f, 14.756f, 9.1556f, 14.2698f, 7.8032f, 13.9811f);
        mPath.cubicTo(6.993f, 13.8043f, 6.1768f, 13.6806f, 5.4137f, 13.6894f);
        mPath.close();
        mPath.moveTo(5.4137f, 13.6894f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        mRenderPath.setFillType(android.graphics.Path.FillType.WINDING);
        if (mFillPaint == null) {
            mFillPaint = new Paint();
            mFillPaint.setStyle(Paint.Style.FILL);
            mFillPaint.setAntiAlias(true);
        }
        mFillPaint.setColor(applyAlpha(-13393683, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);

    }

}