package me.jessyan.mvparms.demo.drawables;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.ColorFilter;
import android.graphics.Paint;

import com.github.megatronking.svg.support.SVGRenderer;

/**
 * AUTO-GENERATED FILE.  DO NOT MODIFY.
 * 
 * This class was automatically generated by the
 * SVG-Generator. It should not be modified by hand.
 */
public class ic_login_et_delete extends SVGRenderer {

    public ic_login_et_delete(Context context) {
        super(context);
        mAlpha = 1.0f;
        mWidth = dip2px(24.0f);
        mHeight = dip2px(24.0f);
    }

    @Override
    public void render(Canvas canvas, int w, int h, ColorFilter filter) {
        final float scaleX = w / 24.0f;
        final float scaleY = h / 24.0f;
        
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(12.0f, 20.0f);
        mPath.cubicTo(7.5817f, 20.0f, 4.0f, 16.4183f, 4.0f, 12.0f);
        mPath.cubicTo(4.0f, 7.5817f, 7.5817f, 4.0f, 12.0f, 4.0f);
        mPath.cubicTo(16.4183f, 4.0f, 20.0f, 7.5817f, 20.0f, 12.0f);
        mPath.cubicTo(20.0f, 16.4183f, 16.4183f, 20.0f, 12.0f, 20.0f);
        mPath.close();
        mPath.moveTo(12.0f, 20.0f);
        mPath.moveTo(15.5838f, 7.1826f);
        mPath.lineTo(11.9571f, 10.8093f);
        mPath.lineTo(8.3139f, 7.166f);
        mPath.lineTo(7.1826f, 8.2972f);
        mPath.lineTo(10.8259f, 11.9405f);
        mPath.lineTo(7.1826f, 15.5838f);
        mPath.lineTo(8.3139f, 16.715f);
        mPath.lineTo(11.9571f, 13.0717f);
        mPath.lineTo(15.5838f, 16.6984f);
        mPath.lineTo(16.715f, 15.5671f);
        mPath.lineTo(13.0884f, 11.9405f);
        mPath.lineTo(16.715f, 8.3139f);
        mPath.lineTo(15.5838f, 7.1826f);
        mPath.close();
        mPath.moveTo(15.5838f, 7.1826f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        mRenderPath.setFillType(android.graphics.Path.FillType.EVEN_ODD);
        if (mFillPaint == null) {
            mFillPaint = new Paint();
            mFillPaint.setStyle(Paint.Style.FILL);
            mFillPaint.setAntiAlias(true);
        }
        mFillPaint.setColor(applyAlpha(-3355444, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);

    }

}