package me.jessyan.mvparms.demo.drawables;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.ColorFilter;
import android.graphics.Paint;

import com.github.megatronking.svg.support.SVGRenderer;

/**
 * AUTO-GENERATED FILE.  DO NOT MODIFY.
 * 
 * This class was automatically generated by the
 * SVG-Generator. It should not be modified by hand.
 */
public class ic_openeye extends SVGRenderer {

    public ic_openeye(Context context) {
        super(context);
        mAlpha = 1.0f;
        mWidth = dip2px(16.0f);
        mHeight = dip2px(16.0f);
    }

    @Override
    public void render(Canvas canvas, int w, int h, ColorFilter filter) {
        final float scaleX = w / 16.0f;
        final float scaleY = h / 16.0f;
        
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(7.9849f, 13.852f);
        mPath.cubicTo(3.6061f, 13.852f, 0.0572f, 9.0755f, 0.0572f, 7.5856f);
        mPath.cubicTo(0.0572f, 5.6181f, 3.6061f, 1.3195f, 7.9849f, 1.3195f);
        mPath.cubicTo(12.3641f, 1.3195f, 15.913f, 6.0846f, 15.913f, 7.5856f);
        mPath.cubicTo(15.913f, 9.1535f, 12.3641f, 13.852f, 7.9849f, 13.852f);
        mPath.close();
        mPath.moveTo(7.9849f, 13.852f);
        mPath.moveTo(7.9849f, 2.3105f);
        mPath.cubicTo(4.1534f, 2.3105f, 1.0473f, 5.9464f, 1.0473f, 7.5857f);
        mPath.cubicTo(1.0473f, 8.8274f, 4.1534f, 12.861f, 7.9849f, 12.861f);
        mPath.cubicTo(11.8164f, 12.861f, 14.922f, 8.7644f, 14.922f, 7.5857f);
        mPath.cubicTo(14.922f, 6.3754f, 11.8164f, 2.3105f, 7.9849f, 2.3105f);
        mPath.close();
        mPath.moveTo(7.9849f, 2.3105f);
        mPath.moveTo(7.9849f, 10.5592f);
        mPath.cubicTo(6.3425f, 10.5592f, 5.0113f, 9.228f, 5.0113f, 7.5857f);
        mPath.cubicTo(5.0113f, 5.9442f, 6.3425f, 4.6126f, 7.9849f, 4.6126f);
        mPath.cubicTo(9.6262f, 4.6126f, 10.9579f, 5.9442f, 10.9579f, 7.5857f);
        mPath.cubicTo(10.9579f, 9.228f, 9.6263f, 10.5592f, 7.9849f, 10.5592f);
        mPath.close();
        mPath.moveTo(7.9849f, 10.5592f);
        mPath.moveTo(7.9849f, 5.6036f);
        mPath.cubicTo(6.8898f, 5.6036f, 6.0029f, 6.4908f, 6.0029f, 7.5857f);
        mPath.cubicTo(6.0029f, 8.6807f, 6.8898f, 9.5677f, 7.9849f, 9.5677f);
        mPath.cubicTo(9.0795f, 9.5677f, 9.9669f, 8.6807f, 9.9669f, 7.5857f);
        mPath.cubicTo(9.9669f, 6.4908f, 9.0795f, 5.6036f, 7.9849f, 5.6036f);
        mPath.close();
        mPath.moveTo(7.9849f, 5.6036f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        mRenderPath.setFillType(android.graphics.Path.FillType.WINDING);
        if (mFillPaint == null) {
            mFillPaint = new Paint();
            mFillPaint.setStyle(Paint.Style.FILL);
            mFillPaint.setAntiAlias(true);
        }
        mFillPaint.setColor(applyAlpha(-8749419, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);

    }

}