package me.jessyan.mvparms.demo.drawables;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.ColorFilter;
import android.graphics.Paint;

import com.github.megatronking.svg.support.SVGRenderer;

/**
 * AUTO-GENERATED FILE.  DO NOT MODIFY.
 * 
 * This class was automatically generated by the
 * SVG-Generator. It should not be modified by hand.
 */
public class ic_pin_left_withe extends SVGRenderer {

    public ic_pin_left_withe(Context context) {
        super(context);
        mAlpha = 1.0f;
        mWidth = dip2px(32.0f);
        mHeight = dip2px(32.0f);
    }

    @Override
    public void render(Canvas canvas, int w, int h, ColorFilter filter) {
        final float scaleX = w / 32.0f;
        final float scaleY = h / 32.0f;
        
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(12.6213f, 16.0f);
        mPath.lineTo(20.5607f, 8.0607f);
        mPath.cubicTo(21.1464f, 7.4749f, 21.1464f, 6.5251f, 20.5607f, 5.9393f);
        mPath.cubicTo(19.9749f, 5.3536f, 19.0251f, 5.3536f, 18.4393f, 5.9393f);
        mPath.lineTo(9.4393f, 14.9393f);
        mPath.cubicTo(8.8536f, 15.5251f, 8.8536f, 16.4749f, 9.4393f, 17.0607f);
        mPath.lineTo(18.4393f, 26.0607f);
        mPath.cubicTo(19.0251f, 26.6464f, 19.9749f, 26.6464f, 20.5607f, 26.0607f);
        mPath.cubicTo(21.1464f, 25.4749f, 21.1464f, 24.5251f, 20.5607f, 23.9393f);
        mPath.lineTo(12.6213f, 16.0f);
        mPath.close();
        mPath.moveTo(12.6213f, 16.0f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        mRenderPath.setFillType(android.graphics.Path.FillType.EVEN_ODD);
        if (mFillPaint == null) {
            mFillPaint = new Paint();
            mFillPaint.setStyle(Paint.Style.FILL);
            mFillPaint.setAntiAlias(true);
        }
        mFillPaint.setColor(applyAlpha(-1, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);

    }

}