package me.jessyan.mvparms.demo.drawables;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.ColorFilter;
import android.graphics.Paint;

import com.github.megatronking.svg.support.SVGRenderer;

/**
 * AUTO-GENERATED FILE.  DO NOT MODIFY.
 * 
 * This class was automatically generated by the
 * SVG-Generator. It should not be modified by hand.
 */
public class ic_yellow_exclamation_point extends SVGRenderer {

    public ic_yellow_exclamation_point(Context context) {
        super(context);
        mAlpha = 1.0f;
        mWidth = dip2px(32.0f);
        mHeight = dip2px(32.0f);
    }

    @Override
    public void render(Canvas canvas, int w, int h, ColorFilter filter) {
        final float scaleX = w / 32.0f;
        final float scaleY = h / 32.0f;
        
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(16.0f, 16.0f);
        mPath.rMoveTo(-16.0f, 0.0f);
        mPath.cubicTo(-5.1947514E-16f, 11.758163f, 1.6868602f, 7.685723f, 4.6862917f, 4.6862917f);
        mPath.cubicTo(7.685723f, 1.6868602f, 11.758163f, 7.792127E-16f, 16.0f, 0.0f);
        mPath.cubicTo(20.241837f, -7.792127E-16f, 24.314278f, 1.6868602f, 27.31371f, 4.6862917f);
        mPath.cubicTo(30.313139f, 7.685723f, 32.0f, 11.758163f, 32.0f, 16.0f);
        mPath.cubicTo(32.0f, 20.241837f, 30.313139f, 24.314278f, 27.31371f, 27.31371f);
        mPath.cubicTo(24.314278f, 30.313139f, 20.241837f, 32.0f, 16.0f, 32.0f);
        mPath.cubicTo(11.758163f, 32.0f, 7.685723f, 30.313139f, 4.6862917f, 27.31371f);
        mPath.cubicTo(1.6868602f, 24.314278f, 5.1947514E-16f, 20.241837f, 0.0f, 16.0f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        mRenderPath.setFillType(android.graphics.Path.FillType.EVEN_ODD);
        if (mFillPaint == null) {
            mFillPaint = new Paint();
            mFillPaint.setStyle(Paint.Style.FILL);
            mFillPaint.setAntiAlias(true);
        }
        mFillPaint.setColor(applyAlpha(-13784, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(14.4628f, 4.0f);
        mPath.lineTo(17.5372f, 4.0f);
        mPath.lineTo(17.0083f, 21.2562f);
        mPath.lineTo(14.9587f, 21.2562f);
        mPath.lineTo(14.4628f, 4.0f);
        mPath.close();
        mPath.moveTo(14.4628f, 4.0f);
        mPath.moveTo(15.9835f, 23.6694f);
        mPath.cubicTo(16.5455f, 23.6694f, 17.0413f, 23.8347f, 17.438f, 24.2314f);
        mPath.cubicTo(17.8017f, 24.595f, 18.0f, 25.0579f, 18.0f, 25.6198f);
        mPath.cubicTo(18.0f, 26.2149f, 17.8017f, 26.6777f, 17.438f, 27.0413f);
        mPath.cubicTo(17.0413f, 27.405f, 16.5455f, 27.6033f, 15.9835f, 27.6033f);
        mPath.cubicTo(15.4215f, 27.6033f, 14.9587f, 27.405f, 14.562f, 27.0413f);
        mPath.cubicTo(14.1653f, 26.6446f, 14.0f, 26.1818f, 14.0f, 25.6198f);
        mPath.cubicTo(14.0f, 25.0579f, 14.1653f, 24.595f, 14.562f, 24.2314f);
        mPath.cubicTo(14.9587f, 23.8347f, 15.4215f, 23.6694f, 15.9835f, 23.6694f);
        mPath.close();
        mPath.moveTo(15.9835f, 23.6694f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        mRenderPath.setFillType(android.graphics.Path.FillType.EVEN_ODD);
        mFillPaint.setColor(applyAlpha(-1, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);

    }

}